Added Categories, Modified files & Installed NuGetPackage.
Added: Controllers, Interfaces, Migrations, Models, Repositories, ViewModels, Views

Modifed: ApplicationDbContext, Views, SharedViews, Program.cs

Installed (Read Note): Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation

[!Note]: The installed package and modified service in Program.cs is for a error CS8032. A Temp folder (TSF Temp) was also deleted externally from desktop. The error is resolved. For now. Not necessary for project.

[!Success]: Migration complete! Enum is replaced by database table. Further project progress will be made here.